import { useState } from 'react'
import { signInWithGoogle } from '../auth'
import { stores } from '../data'
import { saveProfile } from '../repository'
import type { StoreId, UserProfile } from '../types'

export function Welcome({ hasLiveSession, liveEnabled, onDemo, onLive, showSignIn = false }: { hasLiveSession: boolean; liveEnabled: boolean; onDemo: () => void; onLive: () => void; showSignIn?: boolean }) { const [error, setError] = useState(''); const secure = async () => { if (hasLiveSession) { onLive(); return }; try { await signInWithGoogle(); onLive() } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to sign in securely.') } }; return <div className="sign-in"><div className="sign-card"><span className="brand-mark">PQH</span><p className="eyebrow">MONTANA PERFORMANCE HUB</p><h1>{showSignIn ? 'Secure access.' : 'Welcome.'}</h1><p>{showSignIn ? 'Use your Cricket Google account to open your live workspace.' : 'Choose a secure live workspace or explore the app with sample Montana team data.'}</p><button className="primary wide" onClick={() => void secure()} disabled={!liveEnabled}>{hasLiveSession ? 'Open live workspace' : 'Sign in securely with Google'}</button>{!liveEnabled && <small>Live access has not been configured yet. Demo mode is available now.</small>}<button className="secondary wide" onClick={onDemo}>Explore demo</button><small>Demo mode uses sample data on this device only and never changes the live workspace.</small>{error && <p className="error-copy">{error}</p>}</div></div> }

export function LoadingCard({ label }: { label: string }) { return <div className="sign-in"><div className="sign-card"><span className="brand-mark">PQH</span><h1>{label}</h1><p>Montana PQH Team is preparing your secure workspace.</p></div></div> }

export function Onboarding({ userId, email, name }: { userId: string; email: string; name: string }) { const [profile, setProfile] = useState<UserProfile>({ uid: userId, fullName: name, workEmail: email, personalGoogleEmail: email, cellPhone: '', jobTitle: '', storeId: 'helena', role: 'employee', status: 'pending' }); const [saving, setSaving] = useState(false); const ready = profile.fullName.trim() && profile.workEmail.trim() && profile.cellPhone.trim() && profile.jobTitle.trim(); const submit = async () => { if (!ready) return; setSaving(true); try { await saveProfile(profile) } finally { setSaving(false) } }; return <div className="sign-in"><div className="sign-card"><span className="brand-mark">PQH</span><p className="eyebrow">PROFILE SETUP</p><h1>Welcome to the team.</h1><p>Complete your work profile. A manager will confirm your store and access level.</p><div className="profile-form"><label>Full name<input value={profile.fullName} onChange={e => setProfile({ ...profile, fullName: e.target.value })}/></label><label>Cell phone<input type="tel" value={profile.cellPhone} onChange={e => setProfile({ ...profile, cellPhone: e.target.value })}/></label><label>Work email<input type="email" value={profile.workEmail} onChange={e => setProfile({ ...profile, workEmail: e.target.value })}/></label><label>Google email<input type="email" value={profile.personalGoogleEmail} disabled/></label><label>Job title<input value={profile.jobTitle} onChange={e => setProfile({ ...profile, jobTitle: e.target.value })}/></label><label>Store<select value={profile.storeId} onChange={e => setProfile({ ...profile, storeId: e.target.value as StoreId })}>{stores.map(store => <option key={store.id} value={store.id}>{store.name}</option>)}</select></label><button className="primary wide" disabled={!ready || saving} onClick={() => void submit()}>{saving ? 'Saving…' : 'Submit profile for approval'}</button></div></div></div> }
