import { BarChart3, CalendarDays, CheckCircle2, ClipboardList, Home, MapPin, Target, Trophy, Users } from 'lucide-react'
import type { ComponentType } from 'react'

export type Page = 'home' | 'daily' | 'dashboard' | 'goals' | 'milestones' | 'leaderboard' | 'schedule' | 'storeSchedule' | 'open' | 'employees' | 'profile'
type NavItem = { page: Page; label: string; icon: ComponentType<{ size?: number }> }
export const nav: NavItem[] = [{ page: 'home', label: 'Home', icon: Home }, { page: 'daily', label: 'Daily numbers', icon: ClipboardList }, { page: 'dashboard', label: 'Dashboard', icon: BarChart3 }, { page: 'goals', label: 'Goals', icon: Target }, { page: 'milestones', label: 'Milestones', icon: CheckCircle2 }, { page: 'leaderboard', label: 'Leaderboard', icon: Trophy }, { page: 'open', label: 'Store status', icon: MapPin }]

export function NavButton({ item, active, onClick }: { item: NavItem; active: boolean; onClick: (page: Page) => void }) { const Icon = item.icon; return <button className={active ? 'nav-item active' : 'nav-item'} onClick={() => onClick(item.page)}><Icon size={18}/><span>{item.label}</span></button> }
export function SideNav({ page, onClick, isManager }: { page: Page; onClick: (page: Page) => void; isManager: boolean }) { return <><p className="eyebrow">WORKSPACE</p>{nav.map(item => <NavButton key={item.page} item={item} active={page === item.page} onClick={onClick}/>) }<button className={page === 'schedule' ? 'nav-item active' : 'nav-item'} onClick={() => onClick('schedule')}><CalendarDays size={18}/><span>My Schedule</span></button><button className={page === 'storeSchedule' ? 'nav-item active' : 'nav-item'} onClick={() => onClick('storeSchedule')}><Users size={18}/><span>Store Schedule</span></button>{isManager && <><p className="eyebrow section-label">ADMINISTRATION</p><button className={page === 'employees' ? 'nav-item active' : 'nav-item'} onClick={() => onClick('employees')}><Users size={18}/><span>Employees</span></button></>}</> }
